name: Actualizar Pipeline

on:
  schedule:
    - cron: '50 7 * * 1-5'    # Lunes a viernes a las 7:50h Madrid
      timezone: 'Europe/Madrid'
    - cron: '50 12 * * 1-5'   # Lunes a viernes a las 12:50h Madrid
      timezone: 'Europe/Madrid'
    - cron: '50 17 * * 1-5'   # Lunes a viernes a las 17:50h Madrid
      timezone: 'Europe/Madrid'
  workflow_dispatch:        # Permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Generar pipeline
        env:
          ZOHO_CLIENT_ID:     ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
        run: python pipeline.py

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
